@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZW1pbGlhbm9sZXphbWFAeWFob28uY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiS2lyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJpc3MiOiJFZmZvcnQiLCJhdWQiOiJFZmZvcnRVc2VycyIsImlhdCI6MTcxNzUxMjMxMiwiZXhwIjoxNzE3NTEzNTEyfQ.HucD36fvD4In-rQStfZftC1NgHsVotKbpJqIVJv2ivQ


###

GET http://localhost:3000/api/dailyroutines

###

GET http://localhost:3000/api/dailyroutines/4

###

POST http://localhost:3000/api/dailyroutines
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "name": "Rutina Buenisima"
}

###

PUT http://localhost:3000/api/dailyroutines/4
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "name": "Rutina Pecho Perra"
}

###

POST http://localhost:3000/api/dailyroutines/4/exercises
Content-Type: application/json
Authorization: Bearer {{ token }}


{
    "exercises": [
        {
            "exerciseId": 4,
            "series": 23,
            "repetitions": 1
        }
    ]
}

###

PUT http://localhost:3000/api/dailyroutines/4/exercises
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "exercises": [
        {
            "exerciseId": 4,
            "series": 23,
            "repetitions": 1
        }
    ]
}