###

GET http://localhost:3000/api/muscles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6ImV4YW1wbGVVc2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQm9keUJ1aWxkZXIiLCJpc3MiOiJFZmZvcnQiLCJhdWQiOiJFZmZvcnRVc2VycyIsImlhdCI6MTcxNjU5NTI1NiwiZXhwIjoxNzE2NTk2NDU2fQ.57yAqPm9JPGRNdnqj9ltcmgzpaGQM8nI0W50rzfHhnY

###

GET http://localhost:3000/api/muscles/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6ImV4YW1wbGVVc2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQm9keUJ1aWxkZXIiLCJpc3MiOiJFZmZvcnQiLCJhdWQiOiJFZmZvcnRVc2VycyIsImlhdCI6MTcxNjMxODUzMCwiZXhwIjoxNzE2MzE5NzMwfQ.P5MlG9UxvGbQJDID_6yb25kg8s662UKWc-JX2-DO7F0

###

POST http://localhost:3000/api/muscles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6ImV4YW1wbGVVc2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQm9keUJ1aWxkZXIiLCJpc3MiOiJFZmZvcnQiLCJhdWQiOiJFZmZvcnRVc2VycyIsImlhdCI6MTcxNjMxODUzMCwiZXhwIjoxNzE2MzE5NzMwfQ.P5MlG9UxvGbQJDID_6yb25kg8s662UKWc-JX2-DO7F0

{
    "muscleName": "shoulder"
}

###

PUT http://localhost:3000/api/muscles/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6ImV4YW1wbGVVc2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQm9keUJ1aWxkZXIiLCJpc3MiOiJFZmZvcnQiLCJhdWQiOiJFZmZvcnRVc2VycyIsImlhdCI6MTcxNjMxODUzMCwiZXhwIjoxNzE2MzE5NzMwfQ.P5MlG9UxvGbQJDID_6yb25kg8s662UKWc-JX2-DO7F0

{
    "muscleName": "head"
}

###

DELETE http://localhost:3000/api/muscles/36
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6ImV4YW1wbGVVc2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQm9keUJ1aWxkZXIiLCJpc3MiOiJFZmZvcnQiLCJhdWQiOiJFZmZvcnRVc2VycyIsImlhdCI6MTcxNjU5NTI1NiwiZXhwIjoxNzE2NTk2NDU2fQ.57yAqPm9JPGRNdnqj9ltcmgzpaGQM8nI0W50rzfHhnY

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "passW3Se?a#111"
}