@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZXhhbXBsZXc5OUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6ImV4YW1wbGVVc2VyOTkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUcmFpbmVyIiwiaXNzIjoiRWZmb3J0IiwiYXVkIjoiRWZmb3J0VXNlcnMiLCJpYXQiOjE3MTg5Mjk4NzMsImV4cCI6MTcxODkzMTA3M30.s9ionC6TxeLP_Bl3Tro__aohfH-pSD_vL7rOUuo6Cqg

GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer {{ token }}

###

GET http://localhost:3000/api/users/Cesarele23
Content-Type: application/json
Authorization: Bearer {{ token }}

###

GET http://localhost:3000/api/userTypes

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password123",
    "username": "exampleUser",
    "name": "John",
    "lastname": "Doe",
    "dateOfBirth": "1990-01-01",
    "userType": "BodyBuilder"
}

###

PUT http://localhost:3000/api/users/exampleUser
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "email": "example3@example.com",
    "username": "elbuencarlos",
    "name": "John",
    "lastname": "Doe",
    "weight": 75.5,
    "height": 180,
    "bio": "de",
    "password": "dssdw",
    "dateOfBirth": "1912",
    "userType": "ad"
}

###

DELETE http://localhost:3000/api/users/exampleUser

###

POST http://localhost:3000/api/users/Kir/files/1
Content-Type: application/json
Authorization: Bearer {{ token }}

###


GET http://localhost:3000/api/users/Cesarele23/dailyroutines
Content-Type: application/json
Authorization: Bearer {{ token }}

###

POST http://localhost:3000/api/users/Cesarele23/dailyroutines/4
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "isOwner": true
}

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "emilianolezama789@example.com",
    "password": "password123",
    "username": "exampleUser",
    "name": "John",
    "lastname": "Doe",
    "dateOfBirth": "1990-01-01",
    "userType": "Trainer"
}

###