@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZW1pbGlhbm9sZXphbWFAeWFob28uY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiS2lyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJpc3MiOiJFZmZvcnQiLCJhdWQiOiJFZmZvcnRVc2VycyIsImlhdCI6MTcxNzUxMzM4MSwiZXhwIjoxNzE3NTE0NTgxfQ.nAcjt30ivJEYbh_POSj0pDH4nG5zHPGvFvDVaXgrT8k

GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer {{ token }}

###

GET http://localhost:3000/api/users/exampleUser2
Content-Type: application/json
Authorization: Bearer {{ token }}

###

GET http://localhost:3000/api/userTypes

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "example@example.com",
    "password": "password123",
    "username": "exampleUser",
    "name": "John",
    "lastname": "Doe",
    "dateOfBirth": "1990-01-01",
    "userType": "BodyBuilder"
}

###

PUT http://localhost:3000/api/users/exampleUser
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "email": "example3@example.com",
    "username": "elbuencarlos",
    "name": "John",
    "lastname": "Doe",
    "weight": 75.5,
    "height": 180,
    "bio": "de",
    "password": "dssdw",
    "dateOfBirth": "1912",
    "userType": "ad"
}

###

DELETE http://localhost:3000/api/users/exampleUser

###

POST http://localhost:3000/api/users/Kir/files/1
Content-Type: application/json
Authorization: Bearer {{ token }}

###


GET http://localhost:3000/api/users/Cesarele23/dailyroutines
Content-Type: application/json
Authorization: Bearer {{ token }}

###

POST http://localhost:3000/api/users/Cesarele23/dailyroutines/4
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "isOwner": true
}

###

POST https://10.211.44.7/effortbackend/api/users
Content-Type: application/json

{
    "email": "emilianolezama789@example.com",
    "password": "password123",
    "username": "exampleUser",
    "name": "John",
    "middlename": "Michael",
    "lastname": "Doe",
    "weight": 75.5,
    "height": 180,
    "dateOfBirth": "1990-01-01",
    "userType": "Trainer"
}

###